[package]
name = "skgpt"
version = "1.0.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "skgpt"
path = "skgpt.rs"
